### DISCUSSION TITLE
期望HTTP POST中添加, bot监听的http端口(config.yml servers.http.port)

### DISCUSSION THREAD

**Discussion by xiguasamall** [howmanybots/onebot#111] [想法 / 建议]
可以添加在请求头中, 避免更改现有的json结构

这样在功能程序中, 无需关心和维护该bot的监听端口, 用请求头携带过来的端口拼接成url
尤其在一个程序连接多个bot时, 优点特别明显, 再也不用手动建立bot和bot监听端口的映射关系了

**Comment by stdrc** [comment]
这个在 HTTP header 里面本来就有 `Host` 字段干这个的吧

**Reply by xiguasamall** [reply]
Host: 127.0.0.1:5701
其实我想要的是127.0.0.1:5700
标题写错了, 是想要http.port

```yaml
  - http:
      # 服务端监听地址
      host: 127.0.0.1
      # 服务端监听端口
      port: 5700 #想要这个东西 
      # 反向HTTP超时时间, 单位秒
      # 最小值为5，小于5将会忽略本项设置
      timeout: 5
      middlewares:
        <<: *default # 引用默认中间件
      # 反向HTTP POST地址列表
      post:
      #- url: '' # 地址
      #  secret: ''           # 密钥
      - url: 127.0.0.1:5701 # 地址
      #  secret: ''          # 密钥
```
