### ISSUE TITLE
C#平台下的反向ws服务端目前来说都无法使用

### ISSUE THREAD

**Issue by CBGan** [howmanybots/onebot#7]
目前测试得出失效的框架有：
[frank-bots/cqhttp.Cyan](https://github.com/frank-bots/cqhttp.Cyan) 不支持新版本的协议，反向ws服务端失效
[cqbef/cqhttp.WebSocketReverse.NETCore](https://github.com/cqbef/cqhttp.WebSocketReverse.NETCore)不支持新版本的协议，反向ws服务端有效但无法解析json数据

**Comment by richardchien** [comment]
按理说通信这块应该都是兼容的，你用的 OneBot（CQHTTP）实现是哪个

**Comment by CBGan** [comment]
[cqhttp-mirai](https://github.com/yyuueexxiinngg/cqhttp-mirai)

**Comment by richardchien** [comment]
发一下你的配置文件看看？

**Comment by CBGan** [comment]
```yaml
"1169699211":
  ws_reverse:
    # 可选，是否启用反向客户端，默认不启用
    - enable: true
      # 上报消息格式，string 为字符串格式，array 为数组格式
      postMessageFormat: string
      # 反向Websocket主机
      reverseHost: 127.0.0.1
      # 反向Websocket端口
      reversePort: 9200
      # 访问口令, 默认为空, 即不设置Token
      accessToken: ""
      # 反向Websocket路径
      reversePath: /ws/
      # 可选, 反向Websocket Api路径, 默认为reversePath
      # reverseApiPath: /api/
      # 可选, 反向Websocket Event路径, 默认为reversePath
      # reverseEventPath: /event/
      # 是否使用Universal客户端 默认为true
      useUniversal: true
      # 反向 WebSocket 客户端断线重连间隔，单位毫秒
      reconnectInterval: 3000
```
